### ISSUE TITLE
Generate <details> tag in open mode

### ISSUE THREAD

**Issue by dbuenzli** [ocaml-doc/odoc#24]
`<details>` tags have a significant usability problem in the sense that they break fragment linking and on-page search. Besides I think that in general you are interested in seeing all the defs available to you. Hence I would suggest to generate pages with the `open` tag set. 

This way fragment linking and page search will work when the page is loaded and it will still provide a way for users to quickly hide common definitions if needed.

**Comment by lpw25** [comment]
Firstly, we should stop using `<details>` anyway since they are not respected by all browsers. Probably some simple JavaScript would be better. It seems that Firefox finally gets support in version `49` and Microsoft Edge has it under consideration -- so maybe we can go back to using `<details>` later.

Whether or not to open includes by default is a tricky one. It depends very much on the specific include. Things like `include Monad` and similar where the include specifies membership of a specific interface are probably better closed, whereas things like `include Std_internal` which are just about moving pieces of API around are definitely better open.

So the first thing we should do is add support for `@expanded` and `@unexpanded` tags so the user can specify the right behaviour (to go with `@inlined` which is already supported and just inlines the include so that it is not at all visible).

Then the question is what should be the default. Ideally we want the default to be the thing that is most common, but it is not at all clear to me which kind of include is the more common one. Perhaps the default itself should be specifiable -- at the top of a particular fine with a tag or as a command-line argument, or maybe both.

**Comment by dbuenzli** [comment]
> Things like include Monad and similar where the include specifies membership of a specific interface are probably better closed, whereas things like include Std_internal which are just about moving pieces of API around are definitely better open.

My (long time ago, it may have changed) experience with `javadoc` generated documentation is that not having everything on the same page was quite annoying (a closed detail is equivalent).

Even if you replace details by JavaScript you will still break two important things: linking and built-in browser page search. Both are very important for a good user experience.

I don't see any problem with having e.g. Monad definitions on the page, these are part of the API and I'm actually interested in navigating the module API. It's easy to skip if well delineated (or by closing the detail).

> So the first thing we should do is add support for @expanded and @unexpanded tags so the user can specify the right behaviour
[...]
> Perhaps the default itself should be specifiable

I'd say that these would be rather wrong moves. I prefer if the documentation behaves consistently for the users across all packages. Especially the default should make both links and the browser built-in page search work. Given these constraints there's not much choice.
