### ISSUE TITLE
odd rendering alignment of long module, (vs ocamldoc)

### ISSUE THREAD

**Issue by avsm** [ocaml-doc/odoc#30]
see
http://docs.mirage.io/odoc/omd/Omd/index.html
vs the ocamldoc equivalent:
http://docs.mirage.io/omd/Omd.html

The rendering seems to be oddly placed in Safari in the omd version, with the comments being squeezed to the right hand size.

**Comment by avsm** [comment]
new URL for this (we are now using odoc only) is http://docs.mirage.io/omd/Omd/index.html -- rendering still broken

**Comment by trefis** [comment]
@avsm the rendering changed recently and comparing your link with a locally built ocamldoc version, I don't see much of a difference anymore.
Should we close this?

N.B. from memory the problem was that some constructors of the `element` type took a somewhat big object type as parameter, widening the first column of the table and moving comments to the right. Some of @dbuenzli recent CSS changes seem to have fixed that problem.

**Comment by dbuenzli** [comment]
There are still issues but I opened #82 whose title I hope will be easier to find by potential reporters.
