### ISSUE TITLE
Handling of @tags

### ISSUE THREAD

**Issue by avsm** [ocaml-doc/odoc#33]
See 
http://docs.mirage.io/rresult/Rresult/R/index.html#val-get_error

The text should read:
> get_error r is e if r = Error e and Raises Invalid_argument otherwise.

Also the `return` and `fail` look odd below, as they are not in the ocamldoc version.

**Comment by dbuenzli** [comment]
In fact this is not a bold tag: 

https://github.com/dbuenzli/rresult/blob/5e0a87fae06546396fd885b8e0fd6775d6ff4ee6/src/rresult.mli#L55

It seems rather than `@raise` tags get lost. Also sometimes links and content compare for example:

http://erratique.ch/software/fpath/doc/Fpath
http://docs.mirage.io/fpath/Fpath/index.html

The link "important tips" of `ocamldoc` is lost and truncated to "tips". Also the various links to examples are lost (e.g. http://docs.mirage.io/fpath/Fpath/index.html#val-add_seg) presumably because all the sections with examples are lost.

**Comment by trefis** [comment]
Indeed the tags were getting lost, this is fixed as of https://github.com/ocaml-doc/doc-ock-html/commit/3ee8315faf7c83a1da362a35d873c2f6ba28d6c1 .
And although markup can be discussed and improved, I think we can remove the bug and important tags.

The other "issues" you just reported are unrelated and I will open separate issues to track them.

**Comment by dbuenzli** [comment]
So here's what I suggest for markup: 

1. The enclosing `ul` should be classified as `at-tag`. 
2. The `li` should have no paragraphs, I don't think it's possible for `@tags` to generate paragraphs. 
3. The tag text at the beginning of the `<li>` should not be in `<b>` but `<span>`ned and classified as `at-tag $tagname`.

**Comment by trefis** [comment]
I did `1.` and `3.`.
I reserve `2.` for a later date.
