### ISSUE TITLE
No toplevel index file

### ISSUE THREAD

**Issue by dbuenzli** [ocaml-doc/odoc#6]
providing a way to generate one would be nice.

**Comment by lpw25** [comment]
I think the best way to do this is to add both `index` and `package-index` commands.

The first would take a list of module names, a `--pkg` argument, and (eventually) a file with a toplevel synopsis. It would use these to generate a `index.html` file at the top of the specified package.

The second would take a list of package names and generate an `index.html` at the very top of the directory structure.

It might be good to have a name other than `index` for these commands, since we may want to generate an actual index file at some point as well. (`index.html` being something of a misnomer these days).

**Comment by dbuenzli** [comment]
Note that for `opkg` I plan to generate the `index` file myself in the end, since other useful links can be added in that context  (e.g. links to `CHANGES` files). So this is not urgent.

**Comment by dbuenzli** [comment]
Related to #12.

**Comment by dbuenzli** [comment]
Closing in favour of #12.
