### ISSUE TITLE
From OCamldoc to odoc for a newbie

### ISSUE THREAD

**Issue by xvw** [ocaml-doc/odoc#83]
Using Odoc with Odig is really pleasant, the CSS is more easily customizable and the general workflow is easy to use. But actually, when I want to publish a specific documentation, I have to generate the documentation with `odig odoc`and C/C my specific package to my gh-pages.
This is not really problematic ... I guess I should just commit the entire generated directory and share the links that would point to the specific packages.

I use [this package](https://github.com/xvw/olmi) as an experimenting tool (which has already enabled me to finally start using Jbuilder!)

But out of curiosity, I would like to understand several things:

-  What is really a MLD file (and where can I found some documentation about it), @dbuenzli gave me some fragments of answers on the forum OCaml.

-  How to generate documentation for a complete package? Currently, I use `odoc build ...` and `odoc html ...` on each of the `.cmt` files in the package, then I do not know what to do to generate the index.

-  Can it be used "easily" with Jbuilder? (`jbuilder build @doc` Produces `No rule found for alias doc`)

Thank you in advance for your potential answers!
Sincerely, Xavier.

**Comment by trefis** [comment]
Hi,

1. a `.mld` is just a file whose content respects ocamldoc syntax. At the moment they are used to generate an "index" page for a package, i.e. they are the input of `odoc html -index-for=PKG myfile.mld`.
We plan to extend odoc at some point so you can do things like `{!include foo.mld}` in your doc comments. But that isn't supported yet, nor do we have a date in mind for when support will appear.
2. You should indeed call `odoc compile` on each of the `.cmti` file (or `.cmt` when you don't have a `.cmti`) in dependency order. Each of this invocations should produce a `.odoc` file. 
After which you should indeed call `odoc html` on each of these `.odoc` file (the order doesn't matter anymore at this point).
To generate an "index" page for a given package, you want to use `odoc html -index-for ...` and pass it a `.mld` file.
Finally, you might also want to call `odoc css`.
*N.B.* I would recommend relying on odig or your build system to call odoc for you instead of doing it manually.
3. `jbuilder build @doc` should work since version beta10 of jbuilder. You should go and open an issue on [jbuilder's tracker](https://github.com/janestreet/jbuilder/issues) if it doesn't.

**Comment by xvw** [comment]
Thanks !
